In [8]:
import sys
#!{sys.executable} -m pip install gymnasium[classic-control]

import gymnasium as gym
import matplotlib.pyplot as plt
import numpy as np
import random


In [10]:
env = gym.make("CartPole-v1")
print(env.action_space)
print(env.observation_space)
print(env.action_space.sample())

Discrete(2)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
0


In [11]:
env.reset()

for i in range(100):
   env.render()
   env.step(env.action_space.sample())
env.close()

c:\Users\Abdulrahman Yusuf\miniconda3\envs\dscience\lib\site-packages\gymnasium\envs\classic_control\cartpole.py:215: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(
c:\Users\Abdulrahman Yusuf\miniconda3\envs\dscience\lib\site-packages\gymnasium\envs\classic_control\cartpole.py:180: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


In [13]:
env = gym.make("CartPole-v1", render_mode = "human")
print(env.action_space)
print(env.observation_space)
print(env.action_space.sample())

Discrete(2)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
1


In [14]:
env = gym.make("CartPole-v1", render_mode = "human")
observation, info = env.reset()

for _ in range(100):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
       observation, info = env.reset()

env.close()

In [15]:
env = gym.make("CartPole-v1", render_mode = "human")
observation, info = env.reset()
terminated = False
truncated = False
while not terminated and not truncated:
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)
    print(f"{observation} -> {reward}")

   
env.close()

[ 0.04541239  0.15727599 -0.01231819 -0.29397458] -> 1.0
[ 0.04855791 -0.03766819 -0.01819769 -0.00520194] -> 1.0
[ 0.04780455  0.15770994 -0.01830172 -0.30357045] -> 1.0
[ 0.05095874 -0.03714646 -0.02437313 -0.0167152 ] -> 1.0
[ 0.05021581 -0.23191054 -0.02470744  0.26817918] -> 1.0
[ 0.0455776  -0.03644486 -0.01934385 -0.03219312] -> 1.0
[ 0.04484871  0.15894908 -0.01998772 -0.33091593] -> 1.0
[ 0.04802769  0.35434976 -0.02660603 -0.6298344 ] -> 1.0
[ 0.05511468  0.15960898 -0.03920272 -0.34564787] -> 1.0
[ 0.05830686  0.355266   -0.04611568 -0.6504306 ] -> 1.0
[ 0.06541218  0.1608157  -0.05912429 -0.3726184 ] -> 1.0
[ 0.0686285   0.35672554 -0.06657666 -0.68334216] -> 1.0
[ 0.07576301  0.16258815 -0.08024351 -0.41234025] -> 1.0
[ 0.07901477  0.35875046 -0.08849031 -0.72920316] -> 1.0
[ 0.08618978  0.5549769  -0.10307437 -1.0483733 ] -> 1.0
[ 0.09728932  0.3613624  -0.12404184 -0.78974324] -> 1.0
[ 0.10451657  0.16814232 -0.1398367  -0.53851485] -> 1.0
[ 0.10787942 -0.02476542 -0.150